name: Export and Publish
env:
  BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
  ITCH_GAME: ${{ secrets.ITCH_GAME }}
  ITCH_USER: ${{ secrets.ITCH_USER }}
on:
  push:
    branches: [main]
jobs:
  export_game:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export game
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Export
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ${{ steps.export.outputs.archive_directory }}/*
  deploy-itch:
    needs: export_game
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: ./
      - name: Deploy web build
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          CHANNEL: html5
          PACKAGE: web.zip
